"""HRM module models — imported for Alembic discovery via app.models.__init__."""

from app.modules.hrm.models.attendance_record import AttendanceRecord  # noqa: F401
from app.modules.hrm.models.candidate import Candidate  # noqa: F401
from app.modules.hrm.models.contract import Contract  # noqa: F401
from app.modules.hrm.models.department import Department  # noqa: F401
from app.modules.hrm.models.employee import Employee  # noqa: F401
from app.modules.hrm.models.insurance_record import InsuranceRecord  # noqa: F401
from app.modules.hrm.models.interview import Interview  # noqa: F401
from app.modules.hrm.models.leave_request import LeaveRequest  # noqa: F401
from app.modules.hrm.models.leave_type import LeaveType  # noqa: F401
from app.modules.hrm.models.offer import Offer  # noqa: F401
from app.modules.hrm.models.onboarding_checklist import OnboardingChecklist  # noqa: F401
from app.modules.hrm.models.payroll_record import PayrollRecord  # noqa: F401
from app.modules.hrm.models.position import Position  # noqa: F401
from app.modules.hrm.models.recruitment_request import RecruitmentRequest  # noqa: F401
from app.modules.hrm.models.salary_history import SalaryHistory  # noqa: F401
from app.modules.hrm.models.kpi_template import KpiTemplate  # noqa: F401
from app.modules.hrm.models.kpi_assignment import KpiAssignment  # noqa: F401
from app.modules.hrm.models.performance_review import PerformanceReview  # noqa: F401
from app.modules.hrm.models.review_feedback import ReviewFeedback  # noqa: F401
from app.modules.hrm.models.resignation import Resignation  # noqa: F401
from app.modules.hrm.models.handover_task import HandoverTask  # noqa: F401
from app.modules.hrm.models.exit_interview import ExitInterview  # noqa: F401
from app.modules.hrm.models.asset import Asset  # noqa: F401
from app.modules.hrm.models.asset_assignment import AssetAssignment  # noqa: F401
from app.modules.hrm.models.purchase_request import PurchaseRequest  # noqa: F401
from app.modules.hrm.models.purchase_item import PurchaseItem  # noqa: F401
from app.modules.hrm.models.training_program import TrainingProgram  # noqa: F401
from app.modules.hrm.models.training_enrollment import TrainingEnrollment  # noqa: F401
from app.modules.hrm.models.overtime_request import OvertimeRequest  # noqa: F401
from app.modules.hrm.models.attendance_correction import AttendanceCorrection  # noqa: F401
from app.modules.hrm.models.hrm_document import HrmDocument  # noqa: F401
