"""add_crm_phase1_to_phase7_models

Revision ID: c14c93a1c61f
Revises: 0024
Create Date: 2026-03-14 09:04:11.669813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.core.database  # noqa: F401 — for PORTABLE_JSONB type

# revision identifiers, used by Alembic.
revision: str = 'c14c93a1c61f'
down_revision: Union[str, Sequence[str], None] = '0024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_attachments_entity_id'), 'crm_attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_crm_attachments_workspace_id'), 'crm_attachments', ['workspace_id'], unique=False)
    op.create_table('crm_competitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('price_comparison', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_competitors_deal_id'), 'crm_competitors', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_competitors_workspace_id'), 'crm_competitors', ['workspace_id'], unique=False)
    op.create_table('crm_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=True),
    sa.Column('auto_renewal', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_contracts_account_id'), 'crm_contracts', ['account_id'], unique=False)
    op.create_index(op.f('ix_crm_contracts_deal_id'), 'crm_contracts', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_contracts_workspace_id'), 'crm_contracts', ['workspace_id'], unique=False)
    op.create_table('crm_custom_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'entity_type', 'field_name', name='uq_crm_custom_field')
    )
    op.create_index(op.f('ix_crm_custom_fields_workspace_id'), 'crm_custom_fields', ['workspace_id'], unique=False)
    op.create_table('crm_deal_contact_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'contact_id', name='uq_crm_deal_contact_roles_deal_contact')
    )
    op.create_index(op.f('ix_crm_deal_contact_roles_contact_id'), 'crm_deal_contact_roles', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_deal_contact_roles_deal_id'), 'crm_deal_contact_roles', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_deal_contact_roles_workspace_id'), 'crm_deal_contact_roles', ['workspace_id'], unique=False)
    op.create_table('crm_email_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('merge_tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_email_templates_workspace_id'), 'crm_email_templates', ['workspace_id'], unique=False)
    op.create_table('crm_import_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_import_jobs_workspace_id'), 'crm_import_jobs', ['workspace_id'], unique=False)
    op.create_table('crm_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_notifications_recipient_id'), 'crm_notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_crm_notifications_workspace_id'), 'crm_notifications', ['workspace_id'], unique=False)
    op.create_table('crm_product_services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'code', name='uq_crm_product_services_workspace_code')
    )
    op.create_index(op.f('ix_crm_product_services_workspace_id'), 'crm_product_services', ['workspace_id'], unique=False)
    op.create_table('crm_quotations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('quote_number', sa.String(length=50), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('tax_pct', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_quotations_deal_id'), 'crm_quotations', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_quotations_workspace_id'), 'crm_quotations', ['workspace_id'], unique=False)
    op.create_table('crm_sales_forecasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('committed_amount', sa.Float(), nullable=False),
    sa.Column('best_case_amount', sa.Float(), nullable=False),
    sa.Column('closed_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'owner_id', 'period', name='uq_forecast_workspace_owner_period')
    )
    op.create_index(op.f('ix_crm_sales_forecasts_owner_id'), 'crm_sales_forecasts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_sales_forecasts_workspace_id'), 'crm_sales_forecasts', ['workspace_id'], unique=False)
    op.create_table('crm_quotation_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('product_service_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_service_id'], ['crm_product_services.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['crm_quotations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_quotation_lines_quotation_id'), 'crm_quotation_lines', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_crm_quotation_lines_workspace_id'), 'crm_quotation_lines', ['workspace_id'], unique=False)
    op.create_table('crm_email_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['crm_email_templates.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_email_logs_contact_id'), 'crm_email_logs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_email_logs_workspace_id'), 'crm_email_logs', ['workspace_id'], unique=False)
    op.add_column('accounts', sa.Column('custom_field_values', sa.JSON(), nullable=True))
    op.add_column('activity_logs', sa.Column('data', app.core.database.PORTABLE_JSONB(), nullable=True))
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.create_index('ix_activity_logs_created_at', 'activity_logs', ['created_at'], unique=False)
    op.drop_column('activity_logs', 'changes')
    op.drop_index(op.f('ix_attendance_records_date'), table_name='attendance_records')
    op.create_index(op.f('ix_comments_deleted_at'), 'comments', ['deleted_at'], unique=False)
    op.add_column('contacts', sa.Column('custom_field_values', sa.JSON(), nullable=True))
    op.add_column('crm_tickets', sa.Column('reopen_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_index(op.f('ix_cfd_deleted_at'), table_name='custom_field_definitions')
    op.drop_index(op.f('ix_cfd_project_id'), table_name='custom_field_definitions')
    op.drop_index(op.f('ix_cfd_project_position'), table_name='custom_field_definitions')
    op.create_index(op.f('ix_custom_field_definitions_deleted_at'), 'custom_field_definitions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_custom_field_definitions_project_id'), 'custom_field_definitions', ['project_id'], unique=False)
    op.add_column('deals', sa.Column('competitor_id', sa.Uuid(), nullable=True))
    op.add_column('deals', sa.Column('custom_field_values', sa.JSON(), nullable=True))
    op.add_column('deals', sa.Column('probability_manual', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('exit_interviews', sa.Column('responses', app.core.database.PORTABLE_JSONB(), server_default='{}', nullable=False))
    op.drop_constraint(op.f('exit_interviews_resignation_id_key'), 'exit_interviews', type_='unique')
    op.drop_index(op.f('ix_exit_interviews_resignation_id'), table_name='exit_interviews')
    op.create_index(op.f('ix_exit_interviews_resignation_id'), 'exit_interviews', ['resignation_id'], unique=True)
    op.drop_column('exit_interviews', 'feedback')
    op.create_index(op.f('ix_goals_deleted_at'), 'goals', ['deleted_at'], unique=False)
    op.execute("ALTER TABLE interviews ALTER COLUMN feedback TYPE JSONB USING COALESCE(feedback::jsonb, '{}'::jsonb)")
    op.add_column('leads', sa.Column('custom_field_values', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.add_column('review_feedback', sa.Column('responses', app.core.database.PORTABLE_JSONB(), server_default='{}', nullable=False))
    op.drop_column('review_feedback', 'scores')
    op.drop_constraint(op.f('scoring_configs_workspace_id_key'), 'scoring_configs', type_='unique')
    op.drop_index(op.f('ix_scoring_configs_workspace_id'), table_name='scoring_configs')
    op.create_index(op.f('ix_scoring_configs_workspace_id'), 'scoring_configs', ['workspace_id'], unique=True)
    op.drop_constraint(op.f('sprints_project_id_fkey'), 'sprints', type_='foreignkey')
    op.create_foreign_key(None, 'sprints', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_tasks_recurrence_rule'), table_name='tasks', postgresql_where='(recurrence_rule IS NOT NULL)')
    op.drop_constraint(op.f('tasks_sprint_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_epic_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'sprints', ['sprint_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'tasks', ['epic_id'], ['id'])
    op.drop_constraint(op.f('uq_wms_devices_workspace_serial'), 'wms_devices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_wms_devices_workspace_serial'), 'wms_devices', ['workspace_id', 'serial_number'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_epic_id_fkey'), 'tasks', 'tasks', ['epic_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tasks_sprint_id_fkey'), 'tasks', 'sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_tasks_recurrence_rule'), 'tasks', ['recurrence_rule'], unique=False, postgresql_where='(recurrence_rule IS NOT NULL)')
    op.drop_constraint(None, 'sprints', type_='foreignkey')
    op.create_foreign_key(op.f('sprints_project_id_fkey'), 'sprints', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_scoring_configs_workspace_id'), table_name='scoring_configs')
    op.create_index(op.f('ix_scoring_configs_workspace_id'), 'scoring_configs', ['workspace_id'], unique=False)
    op.create_unique_constraint(op.f('scoring_configs_workspace_id_key'), 'scoring_configs', ['workspace_id'], postgresql_nulls_not_distinct=False)
    op.add_column('review_feedback', sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('review_feedback', 'responses')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('leads', 'custom_field_values')
    op.alter_column('interviews', 'feedback',
               existing_type=app.core.database.PORTABLE_JSONB(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_goals_deleted_at'), table_name='goals')
    op.add_column('exit_interviews', sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_exit_interviews_resignation_id'), table_name='exit_interviews')
    op.create_index(op.f('ix_exit_interviews_resignation_id'), 'exit_interviews', ['resignation_id'], unique=False)
    op.create_unique_constraint(op.f('exit_interviews_resignation_id_key'), 'exit_interviews', ['resignation_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('exit_interviews', 'responses')
    op.drop_column('deals', 'probability_manual')
    op.drop_column('deals', 'custom_field_values')
    op.drop_column('deals', 'competitor_id')
    op.drop_index(op.f('ix_custom_field_definitions_project_id'), table_name='custom_field_definitions')
    op.drop_index(op.f('ix_custom_field_definitions_deleted_at'), table_name='custom_field_definitions')
    op.create_index(op.f('ix_cfd_project_position'), 'custom_field_definitions', ['project_id', 'position'], unique=False)
    op.create_index(op.f('ix_cfd_project_id'), 'custom_field_definitions', ['project_id'], unique=False)
    op.create_index(op.f('ix_cfd_deleted_at'), 'custom_field_definitions', ['deleted_at'], unique=False)
    op.drop_column('crm_tickets', 'reopen_count')
    op.drop_column('contacts', 'custom_field_values')
    op.drop_index(op.f('ix_comments_deleted_at'), table_name='comments')
    op.create_index(op.f('ix_attendance_records_date'), 'attendance_records', ['date'], unique=False)
    op.add_column('activity_logs', sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('ix_activity_logs_created_at', table_name='activity_logs')
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('activity_logs', 'data')
    op.drop_column('accounts', 'custom_field_values')
    op.drop_index(op.f('ix_crm_email_logs_workspace_id'), table_name='crm_email_logs')
    op.drop_index(op.f('ix_crm_email_logs_contact_id'), table_name='crm_email_logs')
    op.drop_table('crm_email_logs')
    op.drop_index(op.f('ix_crm_quotation_lines_workspace_id'), table_name='crm_quotation_lines')
    op.drop_index(op.f('ix_crm_quotation_lines_quotation_id'), table_name='crm_quotation_lines')
    op.drop_table('crm_quotation_lines')
    op.drop_index(op.f('ix_crm_sales_forecasts_workspace_id'), table_name='crm_sales_forecasts')
    op.drop_index(op.f('ix_crm_sales_forecasts_owner_id'), table_name='crm_sales_forecasts')
    op.drop_table('crm_sales_forecasts')
    op.drop_index(op.f('ix_crm_quotations_workspace_id'), table_name='crm_quotations')
    op.drop_index(op.f('ix_crm_quotations_deal_id'), table_name='crm_quotations')
    op.drop_table('crm_quotations')
    op.drop_index(op.f('ix_crm_product_services_workspace_id'), table_name='crm_product_services')
    op.drop_table('crm_product_services')
    op.drop_index(op.f('ix_crm_notifications_workspace_id'), table_name='crm_notifications')
    op.drop_index(op.f('ix_crm_notifications_recipient_id'), table_name='crm_notifications')
    op.drop_table('crm_notifications')
    op.drop_index(op.f('ix_crm_import_jobs_workspace_id'), table_name='crm_import_jobs')
    op.drop_table('crm_import_jobs')
    op.drop_index(op.f('ix_crm_email_templates_workspace_id'), table_name='crm_email_templates')
    op.drop_table('crm_email_templates')
    op.drop_index(op.f('ix_crm_deal_contact_roles_workspace_id'), table_name='crm_deal_contact_roles')
    op.drop_index(op.f('ix_crm_deal_contact_roles_deal_id'), table_name='crm_deal_contact_roles')
    op.drop_index(op.f('ix_crm_deal_contact_roles_contact_id'), table_name='crm_deal_contact_roles')
    op.drop_table('crm_deal_contact_roles')
    op.drop_index(op.f('ix_crm_custom_fields_workspace_id'), table_name='crm_custom_fields')
    op.drop_table('crm_custom_fields')
    op.drop_index(op.f('ix_crm_contracts_workspace_id'), table_name='crm_contracts')
    op.drop_index(op.f('ix_crm_contracts_deal_id'), table_name='crm_contracts')
    op.drop_index(op.f('ix_crm_contracts_account_id'), table_name='crm_contracts')
    op.drop_table('crm_contracts')
    op.drop_index(op.f('ix_crm_competitors_workspace_id'), table_name='crm_competitors')
    op.drop_index(op.f('ix_crm_competitors_deal_id'), table_name='crm_competitors')
    op.drop_table('crm_competitors')
    op.drop_index(op.f('ix_crm_attachments_workspace_id'), table_name='crm_attachments')
    op.drop_index(op.f('ix_crm_attachments_entity_id'), table_name='crm_attachments')
    op.drop_table('crm_attachments')
    # ### end Alembic commands ###
