from fastapi import APIRouter

from app.modules.hrm.routers import (
    asset_assignments,
    assets,
    attendance_corrections,
    attendance_records,
    candidates,
    contracts,
    departments,
    documents,
    employees,
    exit_interviews,
    handover_tasks,
    insurance_records,
    interviews,
    kpi_assignments,
    kpi_templates,
    leave_requests,
    leave_types,
    offers,
    onboarding_checklists,
    overtime_requests,
    payroll_records,
    performance_reviews,
    positions,
    purchase_items,
    purchase_requests,
    recruitment_requests,
    resignations,
    review_feedback,
    salary_history,
    training_enrollments,
    training_programs,
)

hrm_router = APIRouter(prefix="/hrm", tags=["hrm"])

hrm_router.include_router(departments.router)
hrm_router.include_router(employees.router)
hrm_router.include_router(leave_types.router)
hrm_router.include_router(leave_requests.router)
hrm_router.include_router(payroll_records.router)
hrm_router.include_router(positions.router)
hrm_router.include_router(contracts.router)
hrm_router.include_router(salary_history.router)
hrm_router.include_router(recruitment_requests.router)
hrm_router.include_router(candidates.router)
hrm_router.include_router(interviews.router)
hrm_router.include_router(offers.router)
hrm_router.include_router(onboarding_checklists.router)
hrm_router.include_router(attendance_records.router)
hrm_router.include_router(insurance_records.router)
hrm_router.include_router(kpi_templates.router)
hrm_router.include_router(kpi_assignments.router)
hrm_router.include_router(performance_reviews.router)
hrm_router.include_router(review_feedback.router)
hrm_router.include_router(training_programs.router)
hrm_router.include_router(training_enrollments.router)
hrm_router.include_router(resignations.router)
hrm_router.include_router(handover_tasks.router)
hrm_router.include_router(exit_interviews.router)
hrm_router.include_router(assets.router)
hrm_router.include_router(asset_assignments.router)
hrm_router.include_router(purchase_requests.router)
hrm_router.include_router(purchase_items.router)
hrm_router.include_router(overtime_requests.router)
hrm_router.include_router(attendance_corrections.router)
hrm_router.include_router(documents.router)
